# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://yuang-ian.github.io/
baseurl: /
title: Yuang Shi‘s website
author: Shi, Yuang
description: Acadamic Personal Website
avatar: profile.png
email: yuangshi@u.nus.edu
github: Shiyuang-scu # username
# twitter: username
linkedin: yuang-shi-439973163
# stackoverflow: username   #e.g: users/2735833/proton1h1
# medium: username #e.g: NobelPeaceOslo
#Comment out if you don't want disqus
# disqus: username
google: citations?user=ytwibHUAAAAJ&hl=en
google_analytics: UA-143142181-1


# needed for travis-ci build
exclude: [vendor]
