highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://jekyllt.github.io/vitae
author: Fábio Madeira

# edit this section with your information
# jekyllt.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /
title: Yuang Shi's Homepage
name: Yuang Shi
email: yuangshi@u.nus.edu
email_full: mailto:yuangshi@u.nus.edu
# website: github.io/sustain
# website_full: https://jekyllt.github.io/sustain
github: Shiyuang-scu
# twitter: twitter
# tel: +44 0000 000000
# tel_full: tel:+440000000000
google_maps: 'https://goo.gl/maps/CaLE2wcq3y8chyKo8'
address:
  street: COM1, 13, Computing Drive
  postcode: 117417
  city: Singapore
  country: Singapore
google_analytics: UA-143142181-1

# needed for travis-ci build
exclude: [vendor]
